import type { DatabaseSchema } from "@/models/domain";

const now = "2026-03-13T09:00:00.000Z";

export const seedDatabase: DatabaseSchema = {
  users: [
    {
      id: "user-admin",
      email: "admin@spoilifly.local",
      passwordHash:
        "pbkdf2$120000$0ef5993761d323108c47557d1c07a242$2ff042976e9e6242212384f3df2b0f05e7e07c484fb904bac867d71c5e6eb4f289a9ad27d5a0d1b3a8004f769f46a9cd96e841322a0bc5b67286ece14f2ae29a",
      role: "admin",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "user-demo",
      email: "reader@spoilifly.local",
      passwordHash:
        "pbkdf2$120000$30d4953b72d2bbeade65b81aa9715e84$0448be867757af0fd79b8e291c6b6e5f9ee058c43a5708edf2b68364b830e07aa972ae00afdf48598fd7faba89ff84bee3d16b510a565d2454d4744b143c7bbe",
      role: "user",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "user-creator",
      email: "creator@spoilifly.local",
      passwordHash:
        "pbkdf2$120000$30d4953b72d2bbeade65b81aa9715e84$0448be867757af0fd79b8e291c6b6e5f9ee058c43a5708edf2b68364b830e07aa972ae00afdf48598fd7faba89ff84bee3d16b510a565d2454d4744b143c7bbe",
      role: "user",
      createdAt: now,
      updatedAt: now,
    },
  ],
  profiles: [
    {
      userId: "user-admin",
      displayName: "Admin SpoilyFly",
      avatarUrl: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=400&q=80",
      bio: "Supervision du catalogue premium et des médias.",
      createdAt: now,
      updatedAt: now,
    },
    {
      userId: "user-demo",
      displayName: "Lina Reader",
      avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80",
      bio: "Passionnée de fins choc et de théories anime.",
      createdAt: now,
      updatedAt: now,
    },
    {
      userId: "user-creator",
      displayName: "Nox Spoiler",
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
      bio: "Créateur indépendant de spoils premium et organisateur de réunions live.",
      createdAt: now,
      updatedAt: now,
    },
  ],
  categories: [
    { id: "cat-scifi", slug: "science-fiction", name: "Science-fiction" },
    { id: "cat-fantasy", slug: "fantasy", name: "Fantasy" },
    { id: "cat-thriller", slug: "thriller", name: "Thriller" },
    { id: "cat-crime", slug: "crime", name: "Crime" },
    { id: "cat-drama", slug: "drama", name: "Drame" },
    { id: "cat-adventure", slug: "adventure", name: "Aventure" },
  ],
  tags: [
    { id: "tag-time-loop", slug: "time-loop", name: "Boucle temporelle" },
    { id: "tag-betrayal", slug: "betrayal", name: "Trahison" },
    { id: "tag-ending", slug: "ending", name: "Fin" },
    { id: "tag-secret", slug: "secret", name: "Secret" },
    { id: "tag-war", slug: "war", name: "Guerre" },
    { id: "tag-family", slug: "family", name: "Famille" },
    { id: "tag-heist", slug: "heist", name: "Plan" },
    { id: "tag-prophecy", slug: "prophecy", name: "Prophétie" },
    { id: "tag-space", slug: "space", name: "Espace" },
    { id: "tag-magic", slug: "magic", name: "Magie" },
  ],
  works: [
    {
      id: "work-breaking-bad",
      slug: "breaking-bad",
      title: "Breaking Bad",
      description: "Walter White s’enfonce dans le crime jusqu’à transformer toute sa famille et ses alliés en dommages collatéraux.",
      type: "series",
      categoryId: "cat-crime",
      tagIds: ["tag-family", "tag-betrayal", "tag-secret"],
      coverImage: "/covers/breaking-bad.svg",
      releaseYear: 2008,
      spoilZoneLabel: "Lab désertique",
      spoilZoneX: 62,
      spoilZoneY: 41,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "work-game-of-thrones",
      slug: "game-of-thrones",
      title: "Game of Thrones",
      description: "Des familles se déchirent pour le Trône de Fer, pendant qu’une menace surnaturelle progresse au nord du Mur.",
      type: "series",
      categoryId: "cat-fantasy",
      tagIds: ["tag-war", "tag-betrayal", "tag-ending"],
      coverImage: "/covers/game-of-thrones.svg",
      releaseYear: 2011,
      spoilZoneLabel: "Winterfell",
      spoilZoneX: 33,
      spoilZoneY: 29,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "work-interstellar",
      slug: "interstellar",
      title: "Interstellar",
      description: "Une mission spatiale tente de sauver l’humanité tandis que le temps détruit les liens familiaux sur Terre.",
      type: "movie",
      categoryId: "cat-scifi",
      tagIds: ["tag-space", "tag-ending", "tag-secret"],
      coverImage: "/covers/interstellar.svg",
      releaseYear: 2014,
      spoilZoneLabel: "Tesseract",
      spoilZoneX: 71,
      spoilZoneY: 48,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "work-hp-deathly-hallows",
      slug: "harry-potter-deathly-hallows",
      title: "Harry Potter and the Deathly Hallows",
      description: "Le dernier affrontement avec Voldemort révèle le prix réel de l’immortalité et des secrets de Dumbledore.",
      type: "book",
      categoryId: "cat-fantasy",
      tagIds: ["tag-magic", "tag-prophecy", "tag-ending"],
      coverImage: "/covers/harry-potter-deathly-hallows.svg",
      releaseYear: 2007,
      spoilZoneLabel: "Poudlard",
      spoilZoneX: 51,
      spoilZoneY: 57,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "work-dune",
      slug: "dune",
      title: "Dune",
      description: "Paul Atréides entre dans une trajectoire messianique dont le coût humain dépasse de loin sa vengeance personnelle.",
      type: "book",
      categoryId: "cat-scifi",
      tagIds: ["tag-prophecy", "tag-war", "tag-betrayal"],
      coverImage: "/covers/dune.svg",
      releaseYear: 1965,
      spoilZoneLabel: "Sietch Tabr",
      spoilZoneX: 58,
      spoilZoneY: 66,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "work-attack-on-titan",
      slug: "attack-on-titan",
      title: "Attack on Titan",
      description: "Le monde derrière les murs transforme complètement le sens du conflit initial et la figure d’Eren.",
      type: "anime",
      categoryId: "cat-thriller",
      tagIds: ["tag-war", "tag-secret", "tag-ending"],
      coverImage: "/covers/attack-on-titan.svg",
      releaseYear: 2013,
      spoilZoneLabel: "Paths",
      spoilZoneX: 26,
      spoilZoneY: 74,
      createdAt: now,
      updatedAt: now,
    },
  ],
  spoilers: [
    {
      id: "spoil-breaking-bad-1",
      workId: "work-breaking-bad",
      title: "Hank découvre enfin qui est Heisenberg",
      teaser: "Un détail banal dans une salle de bain fait tomber la façade que Walter croyait imprenable.",
      premiumContent: "Hank lit le livre dédicacé par Gale et comprend que Walt est Heisenberg. Cette découverte lance la dernière guerre familiale et criminelle de la série.",
      level: "major",
      tagIds: ["tag-secret", "tag-family"],
      mediaIds: [],
      priceCents: 490,
      creatorUserId: "user-creator",
      status: "published",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "spoil-breaking-bad-2",
      workId: "work-breaking-bad",
      title: "La fin de Walter White",
      teaser: "Le dernier plan boucle sa trajectoire de professeur humilié à homme détruit par sa propre légende.",
      premiumContent: "Walter revient, libère Jesse, avoue à Skyler qu’il a agi pour lui-même, puis meurt dans le laboratoire après avoir éliminé le gang de Jack.",
      level: "ending",
      tagIds: ["tag-ending", "tag-family"],
      mediaIds: [],
      priceCents: 690,
      creatorUserId: "user-creator",
      status: "published",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "spoil-got-1",
      workId: "work-game-of-thrones",
      title: "L’identité de Jon Snow",
      teaser: "Une révélation tardive change la légitimité dynastique de tout Westeros.",
      premiumContent: "Jon est le fils de Lyanna Stark et de Rhaegar Targaryen. Ned l’a protégé en le faisant passer pour son bâtard.",
      level: "major",
      tagIds: ["tag-secret", "tag-prophecy"],
      mediaIds: [],
      priceCents: 550,
      creatorUserId: "user-creator",
      status: "published",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "spoil-got-2",
      workId: "work-game-of-thrones",
      title: "Daenerys détruit Port-Réal",
      teaser: "La victoire tant attendue bascule brutalement dans un massacre impossible à réparer.",
      premiumContent: "Après la reddition, Daenerys brûle Port-Réal et ses civils. Jon finit par la tuer pour empêcher un règne de terreur.",
      level: "ending",
      tagIds: ["tag-war", "tag-ending"],
      mediaIds: [],
      priceCents: 790,
      creatorUserId: "user-creator",
      status: "published",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "spoil-interstellar-1",
      workId: "work-interstellar",
      title: "Le fantôme de Murph",
      teaser: "Les phénomènes dans la chambre ne viennent pas d’une entité extérieure classique.",
      premiumContent: "Le “fantôme” est Cooper lui-même depuis le tesseract, manipulant la gravité pour envoyer les données qui sauveront l’humanité.",
      level: "major",
      tagIds: ["tag-space", "tag-secret"],
      mediaIds: [],
      priceCents: 590,
      creatorUserId: "user-creator",
      status: "published",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "spoil-hp-1",
      workId: "work-hp-deathly-hallows",
      title: "Harry est lui-même un Horcruxe",
      teaser: "La survie répétée de Harry s’explique par un lien plus sombre qu’une simple protection maternelle.",
      premiumContent: "Une partie de l’âme de Voldemort vit en Harry depuis Godric’s Hollow. Harry doit accepter sa propre mort pour détruire ce fragment.",
      level: "major",
      tagIds: ["tag-secret", "tag-magic"],
      mediaIds: [],
      priceCents: 490,
      creatorUserId: "user-creator",
      status: "published",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "spoil-dune-1",
      workId: "work-dune",
      title: "Paul devient l’empereur",
      teaser: "Le jeune héritier ne se contente pas de survivre: il absorbe le système qu’il prétend combattre.",
      premiumContent: "Paul force l’Empereur à lui céder le pouvoir en exploitant les Fremen, les vers et la dépendance à l’épice, ouvrant la voie au jihad à venir.",
      level: "ending",
      tagIds: ["tag-war", "tag-prophecy"],
      mediaIds: [],
      priceCents: 690,
      creatorUserId: "user-creator",
      status: "published",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "spoil-aot-1",
      workId: "work-attack-on-titan",
      title: "Le sous-sol et le vrai monde",
      teaser: "Le secret le plus attendu ne donne pas seulement une réponse, il change toute l’échelle du récit.",
      premiumContent: "Le sous-sol révèle l’existence de Marley et du peuple eldien hors des murs. Les Titans ne sont qu’un front d’un conflit géopolitique mondial.",
      level: "major",
      tagIds: ["tag-secret", "tag-war"],
      mediaIds: [],
      priceCents: 590,
      creatorUserId: "user-creator",
      status: "published",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "spoil-aot-2",
      workId: "work-attack-on-titan",
      title: "Eren déclenche le Grand Terrassement",
      teaser: "Le protagoniste franchit un seuil qui le fait passer de victime à menace globale.",
      premiumContent: "Eren utilise le pouvoir du Titan Originel pour lancer le Grand Terrassement et exterminer une grande partie du monde extérieur avant d’être stoppé par ses proches.",
      level: "ending",
      tagIds: ["tag-ending", "tag-war"],
      mediaIds: [],
      priceCents: 790,
      creatorUserId: "user-creator",
      status: "published",
      createdAt: now,
      updatedAt: now,
    },
  ],
  packs: [
    {
      id: "pack-breaking-bad",
      workId: "work-breaking-bad",
      title: "Pack fin de Breaking Bad",
      description: "Les révélations majeures et la fin de Walter White.",
      spoilIds: ["spoil-breaking-bad-1", "spoil-breaking-bad-2"],
      priceCents: 990,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "pack-got",
      workId: "work-game-of-thrones",
      title: "Pack complet Westeros",
      description: "Identité de Jon Snow et fin de Daenerys en un seul achat.",
      spoilIds: ["spoil-got-1", "spoil-got-2"],
      priceCents: 1090,
      createdAt: now,
      updatedAt: now,
    },
  ],
  purchases: [],
  entitlements: [],
  media: [
    {
      id: "media-breaking-bad-1",
      ownerType: "work",
      ownerId: "work-breaking-bad",
      kind: "image",
      url: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=1200&q=80",
      alt: "Atmosphère tendue de thriller",
      createdAt: now,
    },
    {
      id: "media-dune-1",
      ownerType: "work",
      ownerId: "work-dune",
      kind: "image",
      url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
      alt: "Désert épique",
      createdAt: now,
    },
  ],
  checkoutSessions: [],
  walletEntries: [
    {
      id: "wallet-1",
      userId: "user-creator",
      amountCents: 3200,
      type: "adjustment",
      sourceType: "meeting",
      sourceId: "meeting-seed",
      description: "Solde initial créateur",
      createdAt: now,
    },
  ],
  conversations: [
    {
      id: "conversation-1",
      participantUserIds: ["user-demo", "user-creator"],
      title: "Débrief spoilers premium",
      createdAt: now,
      updatedAt: now,
    },
  ],
  messages: [
    {
      id: "message-1",
      conversationId: "conversation-1",
      meetingId: null,
      senderUserId: "user-creator",
      content: "J’ai ajouté un nouveau spoil sur Breaking Bad. Dis-moi si tu veux une réunion dédiée.",
      createdAt: now,
    },
    {
      id: "message-2",
      conversationId: "conversation-1",
      meetingId: null,
      senderUserId: "user-demo",
      content: "Oui, surtout pour Game of Thrones et Interstellar.",
      createdAt: now,
    },
    {
      id: "message-3",
      conversationId: null,
      meetingId: "meeting-1",
      senderUserId: "user-creator",
      content: "Bienvenue dans la réunion spoiler. On commence par la trajectoire de Walter White.",
      createdAt: now,
    },
  ],
  meetings: [
    {
      id: "meeting-1",
      workId: "work-breaking-bad",
      hostUserId: "user-creator",
      title: "Réunion spoiler finale Breaking Bad",
      description: "Session live pour discuter du dernier arc, des motivations de Walt et de la fin de Jesse.",
      scheduledAt: "2026-03-30T19:30:00.000Z",
      priceCents: 290,
      status: "scheduled",
      createdAt: now,
    },
    {
      id: "meeting-2",
      workId: "work-dune",
      hostUserId: "user-creator",
      title: "Débrief prophétique Dune",
      description: "Analyse de Paul, des Fremen et de la dérive messianique.",
      scheduledAt: "2026-04-02T20:00:00.000Z",
      priceCents: 350,
      status: "scheduled",
      createdAt: now,
    },
  ],
  meetingAttendees: [
    {
      id: "meeting-attendee-1",
      meetingId: "meeting-1",
      userId: "user-demo",
      joinedAt: now,
    },
  ],
};
